databases:
  - name: RMIS-Database
    databaseName: rmis
    user: ictadmin

services:
  - type: web
    name: amu-rmis
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rmis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false