default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rmis_development

test:
  <<: *default
  database: rmis_test

production:
  <<: *default
  database: rmis_production
  username: rmis
  password: <%= ENV["RMIS_DATABASE_PASSWORD"] %>
