default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: rmis_development
  username: <%= ENV['RMIS_DATABASE_USERNAME'] %>
  password: <%= ENV['RMIS_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: rmis_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: rmis_production
  username: rmis
  password: <%= ENV["RMIS_DATABASE_PASSWORD"] %>
