global_settings:
  name: 'RMIS'
  description: 'Research Management Information System'
  version: '0.0.1'  
system_modules:
  - name: 'Document management'
    key: 'document_management'
    description: 'Manage documents'

  - name: 'Call management'
    key: 'call_management'
    description: 'Manage research calls'